source ~/Dropbox/perso/scripts/dotfiles/bash/env
source ~/Dropbox/perso/scripts/dotfiles/bash/config
source ~/Dropbox/perso/scripts/dotfiles/bash/aliases
export PATH=$PATH:/home/Users/david/Dropbox/perso/scripts


export TODOTXT_DEFAULT_ACTION=ls
